<?php require_once('./config.php');
    require_once('vendor/autoload.php');
?>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Payments using Stripe</title>	
        <script src="https://ajax.aspnetcdn.com/ajax/jQuery/jquery-3.2.1.min.js"></script>
        <script src="https://js.stripe.com/v1/"></script>
</head>
<body>
<h1>Buy Facebook login Script</h1>
<p>Price: 15.00$</p>
<p>Name: How to Login with Facebook Graph API in PHP</p>
 
<form action="charge.php" method="post">
  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<?php echo $stripe['publishable_key']; ?>"
          data-description="Access for a year"
          data-amount="5000"
          data-locale="auto"></script>
</form>


<?php
    if(isset($_POST['action']) && $_POST['action'] == 'stripe') {
 
		global $stripe_options;
 
		// load the stripe libraries
		//require_once('stripe-php/lib/Stripe.php');
 
		// retrieve the token generated by stripe.js
		$token = $_POST['stripeToken'];
                $amount = $_POST['amount']*100;
                $email = $_POST['email'];
 
		// check if we are using test mode
		/*if(isset($stripe_options['test_mode']) && $stripe_options['test_mode']) {
			$secret_key = $stripe_options['test_secret_key'];
		} else {
			$secret_key = $stripe_options['live_secret_key'];
		}*/
                $secret_key = 'sk_test_PHfn4QGQtmI2xHfJ0rcU6H37';
 
		// attempt to charge the customer's card
		try {
			\Stripe\Stripe::setApiKey($secret_key);
                        
                        $customer = \Stripe\Customer::create(array(
                            'email' => $email,
                            'source'  => $token
                        ));
                        
			$charge = \Stripe\Charge::create(array(
                                        'customer' => $customer->id,
					'amount' => $amount, // $10
					'currency' => 'usd',
				)
			);
 
 
			// redirect on successful payment
                        echo '<h1>Successfully charged </h1>';
			//$redirect = add_query_arg('payment', 'paid', $_POST['redirect']);
 
		} catch (Exception $e) {
			// redirect on failed payment
                         echo '<h1>Failed charged </h1>';
			//$redirect = add_query_arg('payment', 'failed', $_POST['redirect']);
		}
 
		// redirect back to our previous page with the added query variable
		//wp_redirect($redirect); exit;
	}
?>

                <form action="" method="POST" id="stripe-payment-form">
                        <div class="form-row">
				<label>Email</label>
                                <input type="email" size="20" autocomplete="off" name="email" class="card-amount"/>
			</div>
                        <div class="form-row">
				<label>Amount</label>
                                <input type="text" size="20" autocomplete="off" name="amount" class="card-amount"/>
			</div>
			<div class="form-row">
				<label>Card Number</label>
				<input type="text" size="20" autocomplete="off" class="card-number"/>
			</div>
			<div class="form-row">
				<label>CVC</label>
				<input type="text" size="4" autocomplete="off" class="card-cvc"/>
			</div>
			<div class="form-row">
				<label>Expiration (MM/YYYY)</label>
				<input type="text" size="2" class="card-expiry-month"/>
				<span> / </span>
				<input type="text" size="4" class="card-expiry-year"/>
			</div>
			<input type="hidden" name="action" value="stripe"/>
<!--			<input type="hidden" name="redirect" value="<?php //echo get_permalink(); ?>"/>
			<input type="hidden" name="stripe_nonce" value="<?php //echo wp_create_nonce('stripe-nonce'); ?>"/>-->
			<button type="submit" id="stripe-submit">Submit Payment</button>
		</form>
		<div class="payment-errors"></div>
 
</body>
<script>
    Stripe.setPublishableKey('pk_test_h02Rzxpcx4TzsUIqRR9Ehdqo');
    function stripeResponseHandler(status, response) {
        if (response.error) {
                    // show errors returned by Stripe
            jQuery(".payment-errors").html(response.error.message);
                    // re-enable the submit button
                    jQuery('#stripe-submit').attr("disabled", false);
        } else {
            var form$ = jQuery("#stripe-payment-form");
            // token contains id, last4, and card type
            var token = response['id'];
            console.log(token);
            // insert the token into the form so it gets submitted to the server
            form$.append("<input type='hidden' name='stripeToken' value='" + token + "'/>");
            // and submit
            form$.get(0).submit();
        }
    }
    jQuery(document).ready(function($) {
            $("#stripe-payment-form").submit(function(event) {
                    // disable the submit button to prevent repeated clicks
                    $('#stripe-submit').attr("disabled", "disabled");

                    // send the card details to Stripe
                    Stripe.createToken({
                            number: $('.card-number').val(),
                            cvc: $('.card-cvc').val(),
                            exp_month: $('.card-expiry-month').val(),
                            exp_year: $('.card-expiry-year').val()
                    }, stripeResponseHandler);

                    // prevent the form from submitting with the default action
                    return false;
            });
    });
</script>
</html>